### ISSUE TITLE
Update to @babel/eslint-parser

### ISSUE THREAD

**Issue by Nargonath** [hapijs/eslint-plugin#26]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: n/a
* *module version*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What problem are you trying to solve?

The internal eslint configuration written in `lab` is going to be ported to this eslint plugin. This config uses `babel-eslint` as its parser however `babel-eslint` is deprecated and replaced by `@babel/eslint-parser`. Since we are doing some rearrangement for the eslint config, we might as well migrate to the new package and remove it from lab dependencies altogether.

#### Do you have a new or modified API suggestion to solve the problem?

- Replace `babel-eslint` by `@babel/eslint-parser`.

**Comment by kanongil** [comment]
Makes sense `babel-eslint` is more than a year old. Remember to add the `requireConfigFile: false` option to the `parserOptions` so it won't error when a module does not contain an `.eslintrc` file.

**Comment by Nargonath** [comment]
Thanks for the tip @kanongil. We do need this option but not for missing `.eslintrc` file but rather for missing `babel` configuration file. The parser defaults to requiring a `babel` configuration file from what I understood from their documentation.

**Comment by Nargonath** [comment]
Closed in #27
